### ISSUE TITLE
Support for adding a preview image

### ISSUE THREAD

**Issue by sreuter** [city41/neosdconv#1]
It would be awesome if the tool would allow to add a custom preview image for the menu.

**Comment by city41** [comment]
It's been a while since I've worked on this tool, but unfortunately I am pretty sure this is not possible.

The NeoSD has the thumbnails built in, and roms choose an existing thumbnail. So basically the thumbnail data is just a single byte indicating which thumbnail to pick: 

https://github.com/city41/neosdconv/blob/master/src/convertRom.ts#L371

Would love to be wrong about this though!

**Comment by sreuter** [comment]
Oh - I think you're right, unless there's some undocumented feature where you can ask the cartridge to load the logo from the SD card. I'll talk to the @terraonion team and see if there're willing to add our game logo to the next fw update instead then :)
