### ISSUE TITLE
Fails to build Bad Apple

### ISSUE THREAD

**Issue by Yorper** [city41/neosdconv#2]
Trying to use this tool to create a .neo of the Bad Apple demo. The output i keep receiving is...

```
C data length 0
P data length 0
S data length 0
M data length 0
V data length 0
neoFile.length 4096
```

Obviously this is not correct. I'd be grateful if you could add support for Bad Apple. I'm sourcing the ROMs directly from Beys google drive.

https://drive.google.com/drive/folders/0BwZTDuyjKFEuNHh5M0dNb0d0ZzQ

Thanks.

**Comment by city41** [comment]
I fixed a couple of problems preventing Bad Apple from converting, but there are still some problems left that I don't understand. Bad Apple is not a normal rom, so I am not sure how to go about converting it.

I posted a reply to your terraonion forum post: https://forums.terraonion.com/viewtopic.php?f=8&t=1460&p=7794#p7794

**Comment by Yorper** [comment]
Any and all help is greatly appreciated. Thank you.

**Comment by city41** [comment]
Unfortunately I'm not sure if I'll be able to figure this one out without some help from Terraonion. I followed the layout of the rom as described in the mame driver file, but so far no luck.

**Comment by Yorper** [comment]
I can’t ask anymore than what you are already doing. Hopefully someone at Terraonion can aid you.

**Comment by city41** [comment]
Turns out Bad Apple worked all along with neosdconv. The key is you must set the NGH number. TerraOnion's NeoBuilder sets the NGH to `bada`. Which looks strange, but it's actually a hex number.

This properly coverts Bad Apple for me:

```
neosdconv -n BadApple -m foo -y 2021 -g Other -s 1 -# bada -i . -o badapplemg.neo
```

I doubt the NGH number has to be bada, I think the real key it just has to be set so it's not zero.

The badapple rom zip file I am using has sha `0dd515b4285ca9cf7e361fde49d036d9d356c172`

**Comment by city41** [comment]
Also, badapple must be loaded into Flash slot 1 or 3 on a Neo SD pro, according to TerraOnion. As far as I know, it does not work on a regular NeoSD.
